[packages]
names = [
	"neovim",
	"git",
	"alacritty",
	"fzf",
	"zsh",
	"clang",
	"make",
	"cmake",
	"tldr",
	"thefuck",
	"httpie",
  "libXft-devel",
  "libX11-devel",
  "libXinerama-devel"
]

[cargo_install]
names = [
	"zoxide",
	"fd-find",
	"duf",
	"ripgrep",
	"bat",
	"exa",
	"starship",
	"rm-improved",
	"sd",
	"procs",
	"bandwhich",
	"macchina"
]

[git]
name='william'
email='william@mail.com'

[dotfile.neovim]
name='neo'
src='~/sergio/dotfile'
github='sergioarg/dotfiles/nvim'
dest='~/.config/nvim'
